CREATE DATABASE chirpy;
USE chirpy;

CREATE TABLE `chirps` (
	id INT NOT NULL AUTO_INCREMENT,
    author VARCHAR(50),
    chirp VARCHAR(255),
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);